### ISSUE TITLE
Use "get_the_archive_title" to change default archive titles

### ISSUE THREAD

**Issue by mandiwise** [redacademy/gen-why-spring-2016#4]
Use the "get_the_archive_title" instead of adding second `<h1>` to your Event Clips and Short Video archive templates.

**Comment by hunterwinter** [comment]
Used the "get_the_archive_title" instead of adding second <h1> to your Event Clips and Short Video archive templates.

**Comment by hunterwinter** [comment]
Used the "get_the_archive_title" instead of adding second <h1> to your Event Clips and Short Video archive templates.

**Comment by hunterwinter** [comment]
Used the "get_the_archive_title" instead of adding second header to Event Clips and Short Video archive templates.

**Comment by hunterwinter** [comment]
Used the "get_the_archive_title" instead of adding second header to Event Clips and Short Video archive templates.
