### ISSUE TITLE
Don't use relative links

### ISSUE THREAD

**Issue by mandiwise** [redacademy/gen-why-spring-2016#6]
For example, in your `content-what-we-do.php` template, line 16 uses a relative link. Make the site more future-proof by dynamically generating an absolute link, e.g.:

```
<a href="<?php echo get_post_type_archive_link( 'projects' ); ?>" >Find Out More</a>
```

**Comment by kurtisyoung** [comment]
Resolved issue. Added the function get_post_type_archive_link to the correct pages to dynamically generate an absolute link to different archive pages.
