### ISSUE TITLE
Remove CSS from "_variables.scss" partial

### ISSUE THREAD

**Issue by mandiwise** [redacademy/gen-why-spring-2016#9]
The CSS underneath your variable declarations in this partial must be moved to a different partial. This isn't a logical place to put this CSS, but more importantly, look at your style.css file in your theme. All of this styles are being compiled into your stylesheet before your reset, which is not desirable. Your reset should always come first.

**Comment by MichaelMini** [comment]
I re-arranging the order of imports in style.scss . The higher priority should be on top.  _normalize.scss is on top now. 
Issue Closed
